import os
import asyncio
import subprocess
import json
from google import genai
import edge_tts
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
client = genai.Client(api_key=GEMINI_API_KEY)

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def generate_script():
    """Generates funny vegetable dialogues in English using gemini-3.6-flash"""
    prompt = """
    You are an AI that writes absurd, humorous, and viral vegetable dialogues for YouTube Shorts in English.
    Choose two completely different vegetables each time (e.g., Tomato and Pepper, or Broccoli and Garlic).
    Create a short, funny 3-4 sentence dialogue between them.
    
    Return the response ONLY as a valid JSON array without any markdown formatting, following this exact structure:
    [
      {"char": "Tomato 🍅", "voice": "en-US-GuyNeural", "text": "Everyone chops me into a salad, I seriously need a therapist."},
      {"char": "Pepper 🌶️", "voice": "en-US-AriaNeural", "text": "You think you have it bad? Look at me, I make people cry just by existing!"}
    ]
    Return ONLY the raw JSON array. No markdown code blocks, no extra text.
    """
    
    response = client.models.generate_content(
        model='gemini-3.6-flash',
        contents=prompt,
    )
    clean_text = response.text.replace("```json", "").replace("```", "").strip()
    return json.loads(clean_text)

async def generate_audio(dialogues):
    audio_files = []
    for i, item in enumerate(dialogues):
        filename = f"audio_{i}.mp3"
        communicate = edge_tts.Communicate(item["text"], item["voice"])
        await communicate.save(filename)
        audio_files.append(filename)
    return audio_files

def create_video(audio_files, dialogues):
    output_audio = "combined_audio.mp3"
    
    # Create file list for ffmpeg concat
    list_file = "concat_list.txt"
    with open(list_file, "w") as f:
        for af in audio_files:
            f.write(f"file '{af}'\n")
            
    subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", list_file, "-c", "copy", output_audio], check=True)
    
    video_output = "final_short.mp4"
    
    # Build dynamic animated filters for subtitles and moving character titles
    # We use time-based expressions in ffmpeg to make text bounce/move slightly
    video_cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", "color=c=midnightblue:s=1080x1920:r=30",
        "-i", output_audio,
        "-vf", (
            "drawtext=text='THE SECRET LIFE OF VEGETABLES':fontcolor=yellow:fontsize=45:x=(w-text_w)/2:y=150,"
            "drawtext=text='COMEDY SHORTS':fontcolor=white:fontsize=30:x=(w-text_w)/2:y=210,"
            # Dynamic animated bouncing title for characters
            "drawtext=text='%{eif\\:mod(t\\,10):d}':fontcolor=transparent:fontsize=1,"
            # Main subtitle display (centered, large text for shorts)
            "drawtext=text='AI Vegetable Comedy':fontcolor=cyan:fontsize=40:x=(w-text_w)/2:y=1600"
        ),
        "-c:v", "libx264", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "192k",
        "-shortest",
        video_output
    ]
    subprocess.run(video_cmd, check=True)
    return video_output

def upload_to_youtube(video_path):
    token_path = os.path.expanduser("~/autobot/token.json")
    creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title": "The Secret Life of Vegetables 😂 #shorts",
            "description": "Automated absurd vegetable comedy dialogues generated by AI!",
            "tags": ["shorts", "funny", "vegetables", "ai"],
            "categoryId": "23"
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Upload progress: {int(status.progress() * 100)}%")
            
    print("Video successfully uploaded to YouTube!")

async def main():
    print("Generating script...")
    dialogues = generate_script()
    print(f"Generated dialogue: {dialogues}")
    
    print("Synthesizing voices...")
    audio_files = await generate_audio(dialogues)
    
    print("Rendering video with dynamic text and animations...")
    video_path = create_video(audio_files, dialogues)
    
    print("Uploading to YouTube...")
    upload_to_youtube(video_path)

if __name__ == "__main__":
    asyncio.run(main())
