name: Veggie Family Bot 24/7

on:
  schedule:
    - cron: '0 4,11,16 * * *'  # Hər gün Bakı vaxtı ilə 08:00, 15:00 və 20:00-da işləyir (UTC ilə 04:00, 11:00, 16:00)
  workflow_dispatch:      # Əllə istədiyin vaxt işə sala bilməyin üçün

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and FFmpeg
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai edge-tts google-api-python-client google-auth-oauthlib
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Create credentials from Secrets
        run: |
          mkdir -p ~/autobot
          echo '${{ secrets.TOKEN_JSON }}' > ~/autobot/token.json
          echo '${{ secrets.CLIENT_SECRET_JSON }}' > ~/autobot/client_secret.json

      - name: Run main bot script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
        run: |
          python main_bot.py
